### ISSUE TITLE
访问链路间的流量传递

### ISSUE THREAD

**Issue by cynial** [alibaba/virtual-environment#10]
遇到个问题请教下，demo 中的链路间流量传递是通过设置环境变量，在代码中显示指定的，这种依赖 代码配置 header 的方式，似乎无法做到链路间流量传递的强一致？

app-js 访问 app-go

```
  - env:
    - name: envMark
      value: dev
    - name: url
      value: http://app-java:8080/demo
```

app-go 访问 app-java

```
    - name: envMark
      value: dev
    - name: url
      value: http://app-java:8080/demo
```

istio 中有个 `SourceLabels`  标记，可以将请求来源作为判断条件，用这个是不是更好呢？

```
# 如果请求来源是带 `virtual-env: dev.proj1` 标签的服务
# 或者请求中包含 `ali-env-mark: dev.proj1` 的标头
# 则路由到 dev.proj1 版本

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-go
spec:
  hosts:
  - app-go
  http:
  - match:
    - sourceLabels:
        virtual-env: dev.proj1
    - headers:
        ali-env-mark:
          exact: dev.proj1
  - route:
    - destination:
        host: app-go
        subset: dev.proj1
    ...
```
这样 app-js (dev.proj1) 访问 app-go，就会自动路由到 app-go (dev.proj1) 版本
