### ISSUE TITLE
生成的virtualservice为啥对port进行了匹配路由

### ISSUE THREAD

**Issue by JayceLau** [alibaba/virtual-environment#13]
```
  http:
    - match:
        - port: 8080
      route:
        - destination:
            host: xxx-gateway
            port:
              number: 8080
            subset: dev
          weight: 100
```
如上

**Comment by linfan** [comment]
已沟通问题上下文，当服务配置有gateway的时候，比如生成了如下virtualservice：

```yaml
spec:
  hosts:
    - gateway.dev.demo.com
  gateways:
    - demo-dev/demo-gateway
  http:
    - match:
        - port: 8080
      route:
        - destination:
            host: srm-gateway-eureka
            port:
              number: 8080
            subset: dev
          weight: 100
```

此时通过域名gateway.dev.demo.com访问网关就会报404。

**修复方案**：

1) 如果Service配置了gateway的annotation，则生成的VirtualService对象不加spec.http.match.port参数

2) 如果Service只有一个目标端口，则生成的VirtualService对象不加spec.http.match.port参数

考虑通用性，暂定使用方案2修复。
