### ISSUE TITLE
url rewrite 规则在多环境下的处理

### ISSUE THREAD

**Issue by cynial** [alibaba/virtual-environment#15]
在实际的使用过程中，总是存在需要对 url 进行重写的情况，如将 `/prefix/abc` 重写为 `/abc` 

在使用 istio gateway 之前，是通过 nginx ingress，在 ingress 层面进行处理的

使用 istio gateway 之后，就变成了需要在 virtual service 层面去处理

但是在多环境的情况下，这个 rewrite 规则写起来很别扭

想看看有没有更通用的方案

**Comment by linfan** [comment]
”但是在多环境的情况下，这个 rewrite 规则写起来很别扭“
为什么会很别扭，举个具体的例子？

**Comment by cynial** [comment]
1. rewrite 规则，所有环境都需要判断、处理

2. 同时要考虑不能单独设置 rewrite，导致流量进入到错误的环境，要在当前的规则基础上加 rewrite 规则

```
# 原来的规则
  - match:
    - headers:
        ali-env-mark:
          exact: dev.proj1
    route:
    - destination:
        host: app-js
        subset: dev-proj1
  - route:
    - destination:
        host: app-js
        subset: dev
```
```
# 添加 rewrite 后的规则

## 新增的配置
### 1. 在每个环境的基础上，再写一份包含了 rewrite 的规则，且需要放在原来的规则的前面
  - match:
    - headers:
        ali-env-mark:
          exact: dev.proj1
      uri:  
        prefix: /prefix/
    rewrite:
      uri: /
    route:
    - destination:
        host: app-js
        subset: dev-proj1

## 原来的配置
  - match:
    - headers:
        ali-env-mark:
          exact: dev.proj1
    route:
    - destination:
        host: app-js
        subset: dev-proj1

## 新增的配置
### 2. 默认的环境，也需要再写一份包含了 rewrite 的规则
  - match:
    - uri:
        prefix: /prefix/
    rewrite:
      uri: /
    route:
    - destination:
        host: app-js
        subset: dev

## 原来的配置
  - route:
    - destination:
        host: app-js
        subset: dev
```

**Comment by cynial** [comment]
除了 rewrite，应该还有很多 virtual service 上的关键字会用到，但是 operator 目前不支持的。可能需要一个 annotation ，去灵活的覆盖这类场景

比如：kt-virtual-environment/rule: "{"match":[{"uri":{"prefix":"/apps/"}}],"rewrite":{"uri":"/"}}"

**Comment by linfan** [comment]
这类场景确实比较复杂，不太可能把VirtualService的所有属性全部适配成一个复杂的annotation。
针对rewrite的问题，`kt-virtual-environment/rule`是个比较可行的方式，考虑在下个版本里加上。

**Comment by linfan** [comment]
fixed in v0.3.2
文档：https://alibaba.github.io/virtual-environment/#/zh-cn/doc/custom-rule?id=自定义virtualservice规则

**Comment by cynial** [comment]
对于 rewrite ，生成的 vs 规则好像不是很完整

原来的规则是这样的话：

```
# 原来的规则
  - match:
    - headers:
        ali-env-mark:
          exact: dev.proj1
    route:
    - destination:
        host: app-js
        subset: dev-proj1
  - route:
    - destination:
        host: app-js
        subset: dev
```

生成的规则应该是：

```
  - match:
    - headers:
        ali-env-mark:
          exact: dev.proj1
      uri:  
        prefix: /prefix/
    - headers:                        ### 实际生成的规则少了这部分
        ali-env-mark:
          exact: dev.proj1
    rewrite:
      uri: /
    route:
    - destination:
        host: app-js
        subset: dev-proj1
  - match:
    - uri:
        prefix: /prefix/
    rewrite:
      uri: /
    route:
    - destination:
        host: app-js
        subset: dev
  - route:                        ### 实际生成的规则少了这部分
    - destination:
        host: app-js
        subset: dev
```
