### ISSUE TITLE
有gateway的情况下，vs中hosts只有域名，没有svc name

### ISSUE THREAD

**Issue by shixiaoge** [alibaba/virtual-environment#27]
svc 配置:
```
.....
metadata:
  annotations:
    kt-virtual-environment/gateways: xxx-a-gateway
    kt-virtual-environment/hosts: xxx.a.com
  name: xxx-a-svc
......

```
vs自动生成配置:
```
spec:
  gateways:
  - xxx-a-gateway
  hosts:
  - xxx.a.com 
  http:
  ..........
```
**这里自动生成的vs规则，hosts中缺少 svc name，使用xxx-a-svc(svc name)调用时无法使用istio的流量策略**
