### ISSUE TITLE
生成的 virtualservice 的 port 值为空

### ISSUE THREAD

**Issue by cynial** [alibaba/virtual-environment#7]
port 是基于什么考虑，不进行设置呢？

遇到个问题，gateway 同时存在 http/https 的话，https 会报 503 错误，如果设置了 port，就正常

```
  spec:
    hosts:
    - test 
    http:
    - route:
      - destination:
          host: test
          port: {}       <---- 值为空
          subset: dev
        weight: 0
```
