### ISSUE TITLE
没有 gateway 的配置入口

### ISSUE THREAD

**Issue by cynial** [alibaba/virtual-environment#9]
目前 host 是自动填充 service 的 name

对于需要暴露给外部使用的服务，没有 gateway 的配置入口

不知道能不能将 gateway 作为一个可选的配置项？包括 gateway 的名字和 host 域名

```
  spec:
    hosts:
    - test            <---- host 被自动填充，无法更改
    http:
    - route:
      - destination:
          host: test
          port: {}       
          subset: dev
        weight: 0
```

```
  spec:
    gateways:           -|
    - test-gateway       |
    hosts:               |---- 希望能填充 gateway 和域名
    - test.com          -|
    http:
    - route:
      - destination:
          host: test
          port: {}
          subset: dev
        weight: 0
```

**Comment by linfan** [comment]
@cynial 有什么具体建议吗？
目前想到的方案是在Service对象上增加两个可选的Annotation，比如：
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kt-virtual-environment/gateways: test-gateway,test2-gateway
    kt-virtual-environment/hosts: test.com,test2.com
```
